"""Add Default Time Columns

Revision ID: 36597f1780ea
Revises: d3786ce88d2e
Create Date: 2023-03-16 14:16:00.883573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36597f1780ea"
down_revision = "d3786ce88d2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("items", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("items", "updated_at")
    op.drop_column("items", "created_at")
    # ### end Alembic commands ###
